name: Sync Gist
on:
  push:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -s https://gist.githubusercontent.com/neuhaus/8a36584d71e4af27a24f7a72ea32ddef/raw/e859cbbe6bba30ac95251a43fabe7ee031d424b9/othello_svg.html \
          -o othello_svg.html
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Sync gist" || true
          git push
